name: .NET-Test-6x-CodeIO
env: 
  CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

on:
  push:
    branches: [ 'master' ]
  pull_request:
    branches: [ 'master' ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: |
          8.0.x
    - name: Restore dependencies
      run: dotnet restore -p:TargetFramework=net8.0 UnitTest
    - name: Build-8.0
      run: dotnet build --framework net8.0 --no-restore UnitTest
    - name: Test-8.0
      run: dotnet test --framework net8.0 --no-build --verbosity normal /p:CollectCoverage=true /p:CoverletOutputFormat=opencover UnitTest
    - name: Codecov coverage upload
      uses: codecov/codecov-action@v3.1.1
